"""add local government

Revision ID: 481387638ae7
Revises: f734a8913aa8
Create Date: 2024-10-04 11:02:05.133271

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '481387638ae7'
down_revision = 'f734a8913aa8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.alter_column('phone_number',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.alter_column('phone_number',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)

    # ### end Alembic commands ###
