"""Add stutus field to doctor_application

Revision ID: 9e4ed3beb9dc
Revises: 481387638ae7
Create Date: 2024-10-04 22:10:55.965285

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e4ed3beb9dc'
down_revision = '481387638ae7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctor_application', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctor_application', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
